/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ltudor' at '2/17/16 11:41 PM' with Gradle 2.8
 *
 * @author ltudor, @date 2/17/16 11:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
